<a href="https://colab.research.google.com/github/Danylo5051/machine-learning-practice/blob/main/%D0%9B%D0%9F1_%D0%A1%D0%B0%D1%82%D0%BA%D0%BE_%D0%94_4_9_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
# Код студента
import numpy as np

print(np.__version__)

2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
# Код студента
arr = np.array([2, 4, 6, 8, 10])

print(arr)
print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
# Код студента
array_zeros = np.zeros(10)
print("Нулі:\n", array_zeros)

array_ones = np.ones(8)
print("Одиниці:\n", array_ones)

array_sevens = np.full(6, 7)
print("Сімки:\n", array_sevens)

Нулі:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Одиниці:
 [1. 1. 1. 1. 1. 1. 1. 1.]
Сімки:
 [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента
arr_1_20 = np.arange(1, 21)
print("Від 1 до 20:\n", arr_1_20)

arr_evens = np.arange(2, 21, 2)
print("\nПарні від 2 до 20:\n", arr_evens)

Від 1 до 20:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Парні від 2 до 20:
 [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
# Код студента
arr_linspace = np.linspace(0, 1, 11)
print("11 чисел від 0 до 1:\n", arr_linspace)

11 чисел від 0 до 1:
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента
matrix = np.arange(1, 13).reshape(3, 4)
print("Матриця:\n", matrix)

Матриця:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента
print("Кількість вимірів (ndim):", matrix.ndim)
print("Форма (shape):", matrix.shape)
print("Загальна кількість елементів (size):", matrix.size)
print("Тип даних елементів (dtype):", matrix.dtype)

Кількість вимірів (ndim): 2
Форма (shape): (3, 4)
Загальна кількість елементів (size): 12
Тип даних елементів (dtype): int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
# Код студента
arr_float = np.array([1.2, 3.5, 5.7, 7.9])
arr_int = arr_float.astype(int)

print(arr_int)

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
# Код студента
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("1.", arr[0])
print("2.", arr[-1])
print("3.", arr[2:6])
print("4.", arr[::2])

1. 10
2. 80
3. [30 40 50 60]
4. [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента
matrix = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]
])

print("1.", matrix[1, 2])
print("2.", matrix[1, :])
print("3.", matrix[:, 2])
print("4.\n", matrix[1:, :2])

1. 7
2. [5 6 7 8]
3. [ 3  7 11]
4.
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
# Код студента
arr = np.arange(1, 16)
arr[5:10] = 0

print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
# Код студента
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Додавання:\n", a + b)
print("Віднімання:\n", a - b)
print("Множення:\n", a * b)
print("Ділення:\n", a / b)

Додавання:
 [11 22 33 44 55]
Віднімання:
 [ -9 -18 -27 -36 -45]
Множення:
 [ 10  40  90 160 250]
Ділення:
 [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
# Код студента
arr = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(arr))
print("Середнє значення:", np.mean(arr))
print("Мінімум:", np.min(arr))
print("Максимум:", np.max(arr))
print("Медіана:", np.median(arr))
print("Стандартне відхилення:", np.std(arr))

Сума: 108
Середнє значення: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
# Код студента
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("1.", np.sum(matrix))
print("2.", np.sum(matrix, axis=0))
print("3.", np.sum(matrix, axis=1))
print("4.", np.mean(matrix, axis=0))

1. 45
2. [12 15 18]
3. [ 6 15 24]
4. [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
# Код студента
arr = np.arange(1, 11)

print("Масив:", arr)
print("Квадрат кожного елемента:\n", np.square(arr))
print("Квадратний корінь кожного елемента:\n", np.sqrt(arr))
print("Натуральний логарифм кожного елемента:\n", np.log(arr))

Масив: [ 1  2  3  4  5  6  7  8  9 10]
Квадрат кожного елемента:
 [  1   4   9  16  25  36  49  64  81 100]
Квадратний корінь кожного елемента:
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральний логарифм кожного елемента:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
# Код студента
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("1.", arr[arr > 15])
print("2.", arr[arr % 2 == 0])
print("3.", arr[(arr >= 10) & (arr <= 30)])

1. [18 21 25 30 34]
2. [12 18 30 34]
3. [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0

print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
# Код студента
np.random.seed(42)
arr_rand = np.random.randint(0, 101, size=20)

count_greater = np.sum(arr_rand > 50)
count_less_equal = np.sum(arr_rand <= 50)

print("Масив:", arr_rand)
print("Більші за 50:", count_greater)
print("Менші або дорівнюють 50:", count_less_equal)

Масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Більші за 50: 12
Менші або дорівнюють 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
# Код студента
arr_24 = np.arange(1, 25)
mat_4x6 = arr_24.reshape(4, 6)
print("1. shape:", mat_4x6.shape)

mat_6x4 = arr_24.reshape(6, 4)
print("2. shape:", mat_6x4.shape)

mat_2x3x4 = arr_24.reshape(2, 3, 4)
print("3. shape:", mat_2x3x4.shape)

1. shape: (4, 6)
2. shape: (6, 4)
3. shape: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
# Код студента
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Вертикально:\n", np.vstack((A, B)))
print("Горизонтально:\n", np.hstack((A, B)))

Вертикально:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтально:
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
matrix = np.arange(1, 13).reshape(3, 4)

flat_flatten = matrix.flatten()
print("flatten():", flat_flatten)

flat_ravel = matrix.ravel()
print("ravel():", flat_ravel)

print("однакові результати :", np.array_equal(flat_flatten, flat_ravel))

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
однакові результати : True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Сума:\n", a + b)
print("Різниця:\n", a - b)
print("a * 3:\n", a * 3)
print("b * 3:\n", b * 3)

Сума:
 [ 3  7 11]
Різниця:
 [1 1 1]
a * 3:
 [ 6 12 18]
b * 3:
 [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_func = np.dot(a, b)
print("np.dot():", dot_func)
dot_oper = a @ b
print("Оператор @:", dot_oper)

np.dot(): 32
Оператор @: 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
v = np.array([3, 4])

norm_v = np.linalg.norm(v)
print("Евклідова норма:", norm_v)

normalized_v = v / norm_v
print("Нормалізований вектор:", normalized_v)
print("Перевірка норми (має бути 1.0):", np.linalg.norm(normalized_v))

Евклідова норма: 5.0
Нормалізований вектор: [0.6 0.8]
Перевірка норми (має бути 1.0): 1.0


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_product = np.cross(a, b)
print("Векторний добуток:", cross_product)

Векторний добуток: [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])

cos_theta = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("Косинус кута:", cos_theta)

angle_rad = np.arccos(cos_theta)
angle_deg = np.degrees(angle_rad)
print("Кут у градусах:", angle_deg)

Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
A = np.array([[1, 2, 3],
              [4, 5, 6]])

transposed_T = A.T
print(".T:\n", transposed_T)

transposed_func = np.transpose(A)
print("\nnp.transpose():\n", transposed_func)

.T:
 [[1 4]
 [2 5]
 [3 6]]

np.transpose():
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
# Код студента
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

elementwise = A * B
print("Поелементний добуток:\n", elementwise)
matrix_product = A @ B
print("\nМатричний добуток:\n", matrix_product)

Поелементний добуток:
 [[2 0]
 [3 8]]

Матричний добуток:
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
A = np.array([[4, 7],
              [2, 6]])

det_A = np.linalg.det(A)
print("Визначник:", det_A)

inv_A = np.linalg.inv(A)
print("\nОбернена матриця:\n", inv_A)

identity_matrix = A @ inv_A
print("\nПеревірка (A @ inv_A):\n", np.round(identity_matrix))

Визначник: 10.000000000000002

Обернена матриця:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Перевірка (A @ inv_A):
 [[ 1. -0.]
 [ 0.  1.]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
# Код студента
A = np.array([[2, 1],
              [1, 3]])
b = np.array([5, 6])

solution = np.linalg.solve(A, b)

print("Розв'язок системи:")
print("x =", solution[0])
print("y =", solution[1])

Розв'язок системи:
x = 1.8
y = 1.4


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
identity_matrix = np.eye(4)
print("Одинична матриця 4x4:\n", identity_matrix)

random_matrix = np.random.randint(1, 10, size=(4, 4))
print("\nДовільна матриця 4x4:\n", random_matrix)

result_matrix = random_matrix @ identity_matrix
print("\nРезультат множення:\n", result_matrix)

is_equal = np.array_equal(random_matrix, result_matrix)
print("\nзбігається результат з початковою матрицею :", is_equal)

Одинична матриця 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Довільна матриця 4x4:
 [[7 2 4 9]
 [2 9 5 2]
 [4 7 8 3]
 [1 4 2 8]]

Результат множення:
 [[7. 2. 4. 9.]
 [2. 9. 5. 2.]
 [4. 7. 8. 3.]
 [1. 4. 2. 8.]]

збігається результат з початковою матрицею : True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
# Код студента
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result = A + 10
print("Результат:\n", result)

Результат:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
# Код студента
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([10, 20, 30])
result = A + v

print("Результат:\n", result)

Результат:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]])

mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)

Z = (A - mu) / sigma
print("Нормалізована матриця (Z-оцінка):\n", Z)

Нормалізована матриця (Z-оцінка):
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
# Код студента
np.random.seed(42)

rand_ints = np.random.randint(1, 101, size=10)
print("1. Цілі числа:", rand_ints)

rand_matrix = np.random.rand(3, 3)
print("\n2. Матриця 3x3:\n", rand_matrix)

rand_normal = np.random.randn(1000)
mean_norm = np.mean(rand_normal)
std_norm = np.std(rand_normal)

print(f"\n3. Нормальний розподіл : {rand_normal[:5]}")
print(f"   Середнє значення: {mean_norm:.4f}")
print(f"   Стандартне відхилення: {std_norm:.4f}")

1. Цілі числа: [52 93 15 72 61 21 83 87 75 75]

2. Матриця 3x3:
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]

3. Нормальний розподіл : [ 0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112]
   Середнє значення: 0.0222
   Стандартне відхилення: 0.9792


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
# Код студента
np.random.seed(42)

grades = np.random.randint(0, 101, size=30)
print("Оцінки:", grades)
print("Середня оцінка:", np.mean(grades))
print("Медіана:", np.median(grades))
print(f"Найвища: {np.max(grades)}, Найнижча: {np.min(grades)}")
passed_count = np.sum(grades >= 60)
print("Кількість студентів з оцінкою >= 60:", passed_count)
excellent_percent = np.mean(grades >= 90) * 100
print(f"Відсоток студентів з оцінкою >= 90: {excellent_percent:.1f}%")

Оцінки: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
Середня оцінка: 50.86666666666667
Медіана: 54.5
Найвища: 99, Найнижча: 1
Кількість студентів з оцінкою >= 60: 13
Відсоток студентів з оцінкою >= 90: 6.7%


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
# Код студента
sales = np.array([[120, 150, 170, 160],
                  [ 80,  90, 100, 110],
                  [200, 180, 210, 230]])

total_sales_per_product = np.sum(sales, axis=1)
print("1. Загальний обсяг продажів кожного товару:", total_sales_per_product)
total_sales_per_month = np.sum(sales, axis=0)
print("2. Загальний обсяг продажів у кожному місяці:", total_sales_per_month)
best_product_index = np.argmax(total_sales_per_product)
print(f"3. Товар із найбільшими продажами: Товар {best_product_index + 1} (обсяг: {total_sales_per_product[best_product_index]})")
best_month_index = np.argmax(total_sales_per_month)
print(f"4. Місяць із найбільшим обсягом продажів: Місяць {best_month_index + 1} (обсяг: {total_sales_per_month[best_month_index]})")
mean_sales_per_product = np.mean(sales, axis=1)
print("5. Середній обсяг продажів кожного товару:", mean_sales_per_product)

1. Загальний обсяг продажів кожного товару: [600 380 820]
2. Загальний обсяг продажів у кожному місяці: [400 420 480 500]
3. Товар із найбільшими продажами: Товар 3 (обсяг: 820)
4. Місяць із найбільшим обсягом продажів: Місяць 4 (обсяг: 500)
5. Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
# Код студента
np.random.seed(42)

matrix = np.random.randint(1, 21, size=(5, 5))
print("Початкова матриця:\n", matrix)
main_diag_sum = np.sum(np.diagonal(matrix))
print("\n1. Сума головної діагоналі:", main_diag_sum)
anti_diag_sum = np.sum(np.diagonal(np.fliplr(matrix)))
print("2. Сума побічної діагоналі:", anti_diag_sum)
max_per_row = np.max(matrix, axis=1)
print("3. Максимальний елемент кожного рядка:", max_per_row)
min_per_col = np.min(matrix, axis=0)
print("4. Мінімальний елемент кожного стовпця:", min_per_col)
mean_val = np.mean(matrix)
print(f"\nСереднє значення матриці: {mean_val:.2f}")
modified_matrix = matrix.copy()
modified_matrix[modified_matrix < mean_val] = 0
print("5. Матриця після заміни елементів:\n", modified_matrix)

Початкова матриця:
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]

1. Сума головної діагоналі: 59
2. Сума побічної діагоналі: 32
3. Максимальний елемент кожного рядка: [20 19 12 17 19]
4. Мінімальний елемент кожного стовпця: [ 2  1  2 11  4]

Середнє значення матриці: 10.52
5. Матриця після заміни елементів:
 [[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
# Код студента
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])

row1 = X[0, :]
row2 = X[1, :]
row3 = X[2, :]

dist_1_2 = np.linalg.norm(row1 - row2)
dist_1_3 = np.linalg.norm(row1 - row3)
dist_2_3 = np.linalg.norm(row2 - row3)

print(f"Відстань між першим і другим рядком: {dist_1_2:.2f}")
print(f"Відстань між першим і третім рядком: {dist_1_3:.2f}")
print(f"Відстань між другим і третім рядком: {dist_2_3:.2f}")

Відстань між першим і другим рядком: 1.73
Відстань між першим і третім рядком: 5.20
Відстань між другим і третім рядком: 6.93


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
# Код студента
np.random.seed(42)

matrix = np.random.randint(1, 10, size=(4, 4))
print("Початкова матриця:\n", matrix)
row_norms = np.linalg.norm(matrix, axis=1, keepdims=True)
normalized_matrix = matrix / row_norms
print("\nНормалізована матриця (кожен рядок має одиничну довжину):\n", np.round(normalized_matrix, 3))
print("\nПеревірка:", np.linalg.norm(normalized_matrix, axis=1))

Початкова матриця:
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]

Нормалізована матриця (кожен рядок має одиничну довжину):
 [[0.564 0.322 0.645 0.403]
 [0.535 0.229 0.535 0.612]
 [0.385 0.308 0.615 0.615]
 [0.349 0.697 0.581 0.232]]

Перевірка: [1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
# Код студента
A = np.array([[ 1,  2,  1],
              [ 2,  1, -1],
              [ 3, -1,  2]])

b = np.array([9, 8, 3])
x = np.linalg.solve(A, b)
print("1. Розв'язок системи (x, y, z):", x)

A_times_x = A @ x
print("2. Результат матричного множення A @ x:", A_times_x)

is_correct = np.allclose(A_times_x, b)
print("3. збігається результат з вектором b", is_correct)

1. Розв'язок системи (x, y, z): [ 2.22222222  3.44444444 -0.11111111]
2. Результат матричного множення A @ x: [9. 8. 3.]
3. збігається результат з вектором b True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
